name: Lint Python

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  lint:
    name: Lint Python
    runs-on: ubuntu-24.04
    steps:
      - name: "Checkout"
        uses: "actions/checkout@v4"

      - name: Set up Python 3.12
        uses: actions/setup-python@v3
        with:
          python-version: "3.12"

      - name: Install uv
        uses: astral-sh/setup-uv@v3

      - name: Run linting on Python code for lambda functions
        run: |
          cd infra/modules/
          uv run ruff check .
          uv run mypy .
